name: geomatikkdagene18
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=9.0.1=py34_1
  - python=3.4.5=0
  - setuptools=27.2.0=py34_1
  - vc=10=0
  - vs2010_runtime=10.00.40219.1=2
  - wheel=0.29.0=py34_0
  - nb_conda=2.0.0=py34_0
  - geojson=2.3.0=py_0
  - geopandas=0.2.1=py34_3
  - mplleaflet=0.0.5=py34_1
